project:
  type: website
  output-dir: docs

website:
  title: "CF"
  favicon: pictures/foil_kreis.png
  navbar:
    background: primary
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: quarto.qmd
        text: Quarto-Projekte
      - href: old.qmd
        text: Frühere Projekte
      - href: poster.qmd
        text: Poster
    right: 
      - href: about.qmd
        text: Über mich
  page-footer:
    background: primary
    left: "Created in 2025"
    center:
      - href: https://github.com/teletrabbie
        icon: github
      - href: https://open.spotify.com/playlist/5uOdtjw9CCVf5dfX6kLa9y?si=9b11daf398e84c66
        icon: spotify
      - href: https://flyingangels.ch/
        icon: person-arms-up
    right:
      - href: https://quarto.org/docs/websites/
        text: "Made with Quarto"

format:
  html:
    theme: lux
    css: styles.css
    toc: false



